name: Terraform Deployment Workflow

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  infrastructure_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Reposiory
        uses: actions/checkout@v6

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4
      
      - name: Initialize Terraform
        env:
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ secrets.TF_BACKEND_KEY }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="encrypt=true" \
            -backend-config="use_lockfile=true"
        working-directory: ./terraform

      - name: Terraform Plan
        env:
          TF_VAR_website_bucket_name: ${{ secrets.WEBSITE_BUCKET_NAME }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        env:
          TF_VAR_website_bucket_name: ${{ secrets.WEBSITE_BUCKET_NAME }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Uploading Files to S3 Bucket
        run: |
          pwd
          ls -la
          aws s3 cp ./index.html s3://${{ secrets.WEBSITE_BUCKET_NAME }}/index.html
          aws s3 cp --recursive ./images s3://${{ secrets.WEBSITE_BUCKET_NAME }}/images/
          aws s3 cp --recursive ./styles s3://${{ secrets.WEBSITE_BUCKET_NAME }}/styles/

      - name: List S3 Buckets
        env: 
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          echo "Listing S3 Buckets in region $AWS_REGION"
          aws s3 ls